config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :todo_lists

  root 'todo_lists#index'

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  def index
    @todo_lists = current_user.todo_lists.all
  end

  def new
    @todo_list = current_user.todo_lists.new
  end

  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)
    if @todo_list.save
      redirect_to todo_lists_path
    else
      render :new
    end
  end

  def update
    if @todo_list.update(todo_list_params)
      redirect_to todo_lists_path
    else
      render :edit
    end
  end

  def destroy
    @todo_list.destroy
    redirect_to todo_lists_path
  end

  private
    def todo_list_params
      params.require(:todo_list).permit(:content, :completed)
    end

    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div data-alert class="alert-box alert">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/todo_list_helper.rb
module TodoListHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Todo List</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <div class="container">
      <% if notice %>
        <div data-alert class="alert-box info">
          <p class="notice"><%= notice %></p>
          <a href="#" class="close">&times;</a>
        </div>
      <% end %>
      <% if alert %>
        <div data-alert class="alert-box info">
          <p class="alert"><%= alert %></p>
          <a href="#" class="close">&times;</a>
        </div>
      <% end %>
       

      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div data-alert class="alert-box warning">     
      <%= @todo_list.errors.full_messages.first %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit "确定", class: "button med" %>
  </div>
<% end %>

app/views/todo_lists/index.html.erb
<div class="user-nav">
  <span class="user-email">
    <%= current_user.email %>
  </span>
  <%= link_to "退出登录", destroy_user_session_path, method: :delete %>
</div>

<h2>待办事项</h2>

<%= link_to "添加任务", new_todo_list_path, class: "button radius", id: "add-todo"%>

<%= div_for(@todo_lists) do |todo| %>
  <%= form_for(todo) do |f| %>
    <%= f.check_box :completed %>

    <span class="todo-content <%= "#{"completed" if todo.completed}" %>"> 
      <%= todo.content -%>
      <%# truncate(todo.content,length: 25) %>
    </span>
   
    <%= f.submit "保存", class: "button med" %>
    <%= link_to '删除', todo, method: :delete,class: "button med alert" %>
  <% end %> <!-- form_for -->
<% end %> <!-- div_for -->

app/views/todo_lists/new.html.erb
<h2>新事项</h2>
<%= render "form" %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>